<!DOCTYPE html>
<html>

<head>
    <style>
        html body {
            font-family: Roboto, 'Segoe UI', Tahoma, sans-serif;
            font-size: 12px;
            line-height: 1rem;
        }

        h4,
        h2 {
            text-align: center;
        }

        table {
            width: 100%;
            border: none;
            border-spacing: 0;
        }

        body {
            padding: 80px 90px 50px 50px;
            background-image: url({{ public_path('img/pgvcl.png') }});
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }

        td {
            padding: 3px;
        }

        @page {
            margin: 0px !important;
        }

        p,li {
            text-align: justify;
        }

        .page-break {
            page-break-before: always;
        }

        .footer_sign {
            position: absolute;
            bottom: 20;
            width: 80%;
            text-align: center;
        }

        .side_sign {
            writing-mode: vertical-lr;
            border-right: solid black 1px;
            display: inline-block;
            padding-top: 170px;
            top: 280;
        }

        .side_sign {
            text-orientation: mixed;
            position: absolute;
            right: 50px;
        }
    </style>
</head>

<body>
    <p style="text-align: center ;"><b><u>SOLAR PROJECT COMMISSION REPORT UNDER PM SURYA GHAR : MUFT BIJLI YOJANA</u></b>
    </p>
    <p style="text-align: center;"><b>Reference:- Gujarat Electricity Regulatory Commission (Net Metering Rooftop Solar
            PV Grid Interactive
            Systems), (Fifth Amendment) Regulations, Notification 10 of 2025 Dtd:- 3.11.2025</b></p>

    <p>Name of Consumer: {{ $order_data->consumer_name }}
        <br />Address: {{ $order_data->address }}
        <br />Consumer No.: {{ $order_data->consumer_number }}
        <br />PMSG: MBY Application No.: {{ $order_data->ragistration_number }}
        <br />Solar PV Capacity (KW): {{ $order_data->register_kw }}
        <br />Date of Commission of project (i.e. Dt. Of Meter installation):
        {{ $order_data->meter_installation_date != null && $order_data->meter_installation_date != '0000-00-00' ? date('d-m-Y', strtotime($order_data->meter_installation_date)) : '__________' }}
    </p>

    <p><b>Dear Sir / Madam,</b></p>
    <p>This is hereby inform you that you have registered and installed Solar Rooftop PV Systems under PM Surya Ghar
        Muft
        Bijli Yojana as per the applicable Provisions of Gujarat Electricity Regulatory Commission (Net Metering Rooftop
        Solar PV Grid Interactive Systems) Regulations and its subsequent amendments, Accordingly PGVCL has released
        your project on Dtd:- ________ for which as notified by Hon’ble GERC vide notification no.10 of 2025</p>

    <p><b>Agreement Period :-</b></p>
    <p>The date of commissioning of Solar Rooftop PV systems i.e Dt:-__________ shall be the date of commencement of
        agreement and be valid up to 25 years or useful life of the Solar PV Systems, whichever is earlier.</p>
    <p><b>Commercial Settlement :</b></p>
    <p>All the commercial settlements under this scheme shall be on provisional basis taking into account the
        notification
        of new Gujarat RE Policy-2023 and as an interim arrangement and subject to change as per further regulation
        /order /decision/amendments issued by GERC from time-to-time.</p>

    <ul>
        <li>In case of net import of energy by the consumer from distribution grid during billing cycle, the energy
            consumed from Distribution Licensee shall be billed as per applicable tariff to respective category of
            consumers
            as approved by the Commission from time to time. The energy generated by Rooftop Solar PV System shall be
            set off against units consumed (not against load/demand) and consumer shall pay demand charges, other
            charges, penalty etc as applicable to other consumers.</li>
        <li>In case of net export of energy by the consumer to distribution grid during billing cycle, Distribution
            Licensee
            shall purchase surplus power, after giving set off against consumption during the billing period, at Rs.
            2.25/Unit
            for the first 5 years from commissioning of project and thereafter for the remaining term of the project at
            75%
            of the simple average of tariff discovered and contracted under competitive bidding process conducted by
            GUVNL for non-park based solar projects in the preceding 6-month period, i.e. either April to September or
            October to March as the case may be, from the commercial operation date (COD) of the project, subject to
            approval of Hon’ble GERC. Such surplus purchase shall be utilized for meeting RPO of Distribution Licensee.
            However, fixed / demand charges, other charges, penalty etc shall be payable as applicable to other
            consumers.</li>
    </ul>

    <p>You are bound with all the terms and conditions of GERC Net Metering Regulations and its subsequent amendments
        for Solar Rooftop PV System from time to time.</p>
    <p>This is for your Kind information and you are hereby inform to acknowledge the same.</p>
<br/>
    <table>
        <tr>
            <td style="width:50%;"></td>
            <td style="width:50%;text-align: right;">
                Deputy/Junior Engineer<br />
                {{ $order_data->subDivisionPDF->name }} Sub-Division
                PGVCL
            </td>
        </tr>
    </table>



    <p style="text-align: center;"><b><u>Acknowledgement</u></b><p>

        <p><b>Acknowledged by :</b> </p>
    <p><b>Name (Consumer or representative) : {{ $order_data->consumer_name }}</b>
        <br /><b>Sign (Consumer or representative)</b>
        <br /><b>Date</b>
        <br /><b>Place</b>
        <br /><b>Mobile No. : {{ $order_data->contact_number }}</b>
    </p>


</body>

</html>
